# Generated by Django 3.2 on 2023-03-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
