# Generated by Django 3.2 on 2023-03-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default="2019-08-24T14:15:22Z"),
            preserve_default=False,
        ),
    ]
